[build.env]
passthrough = [
    "JEANNE_DISCORD_TOKEN",
    "JEANNE_TWITTER_CONSUMER_KEY",
    "JEANNE_TWITTER_CONSUMER_SECRET",
    "JEANNE_ACCESS_CONSUMER_KEY",
    "JEANNE_ACCESS_CONSUMER_SECRET",
]

[target.armv7-unknown-linux-musleabihf]
image = "douman/cross-armv7-unknown-linux-musleabihf:latest"
