name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install Rust Unix
      if: runner.os != 'Windows'
      run: |
        if rustup --version >/dev/null 2>&1; then
            rustup update
        else
             curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
             echo ::add-path::$HOME/.cargo/bin
        fi
    - name: Install Rust Windows
      if: runner.os == 'Windows'
      run: |
        if (Get-Command "rustup" -ErrorAction SilentlyContinue) {
            rustup update
        } else {
            Invoke-WebRequest https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe -OutFile rustup-init.exe
            ./rustup-init.exe -y --profile minimal --default-toolchain stable
            echo ::add-path::%USERPROFILE%\.cargo\bin
        }

    - name: Rust version
      run: |
        cargo --version
        rustc --version

    - name: Check
      env:
        JEANNE_ACCESS_CONSUMER_KEY: ${{ secrets.JEANNE_ACCESS_CONSUMER_KEY }}
        JEANNE_ACCESS_CONSUMER_SECRET: ${{ secrets.JEANNE_ACCESS_CONSUMER_SECRET }}
        JEANNE_TWITTER_CONSUMER_KEY: ${{ secrets.JEANNE_TWITTER_CONSUMER_KEY }}
        JEANNE_TWITTER_CONSUMER_SECRET: ${{ secrets.JEANNE_TWITTER_CONSUMER_SECRET }}
        JEANNE_DISCORD_TOKEN: ${{ secrets.JEANNE_DISCORD_TOKEN }}
      run: cargo check
